🚧 feat(grid): apollo footer redesign
UiPath/angular-components pull request #114
Opened 2020-12-22 16:48 UTC by alexdudescu

2021-01-06 13:46 UTC, toxik requested changes

2021-01-06 13:46 UTC, toxik commented on projects/angular/components/ui-grid/src/components/ui-grid-custom-paginator/ui-grid-custom-paginator.component.html
> +                (click)="onPageIndexChanged(pageIndex - 1)"
these buttons should be disabled when you're on the first page.
please also adhere to the attribute order convention

2021-01-06 13:46 UTC, toxik commented on projects/angular/components/ui-grid/src/components/ui-grid-custom-paginator/ui-grid-custom-paginator.component.html
> +                (click)="onPageIndexChanged(pageCount - 1)"
these buttons should be disabled when you're on the last page.
same as above, please adhere to the attribute order convention

2021-01-06 13:46 UTC, toxik commented on projects/angular/components/ui-grid/src/components/ui-grid-custom-paginator/ui-grid-custom-paginator.component.spec.ts
> +import {
this file doesn't seem to add value, if the tests reside elsewhere let's delete this

2021-01-06 13:46 UTC, toxik commented on projects/angular/components/ui-grid/src/components/ui-grid-custom-paginator/ui-grid-custom-paginator.component.ts
> +import {
there seem to be a problem with the tabbing in these file (and other) – 2 spaces vs 4, please fix this as well before merge

2021-01-07 06:51 UTC, anbalase requested changes

2021-01-07 06:51 UTC, anbalase commented on projects/angular/components/ui-grid/src/components/ui-grid-custom-paginator/ui-grid-custom-paginator.component.html
> +        <span>{{intl.page}} {{ pageIndex + 1 }} / {{ pageCount }}</span>
same here

2021-01-07 06:51 UTC, anbalase commented on projects/angular/components/ui-grid/src/components/ui-grid-custom-paginator/ui-grid-custom-paginator.component.ts
> +    public length = 0;
```suggestion
    public length?: number;
```

2021-01-07 06:51 UTC, anbalase commented on projects/angular/components/ui-grid/src/ui-grid.component.html
> +        [pageIndex]="footer?.state?.pageIndex"
```suggestion
        [pageIndex]="footer!.state?.pageIndex"
```

2021-01-07 06:51 UTC, anbalase commented on projects/angular/components/ui-grid/src/components/ui-grid-custom-paginator/ui-grid-custom-paginator.component.ts
> +    public pageSize = 50;
What happens if this changes? Is the index resetted?

2021-01-07 06:51 UTC, anbalase commented on projects/angular/components/ui-grid/src/components/ui-grid-custom-paginator/ui-grid-custom-paginator.component.ts
> +    public pageSizeOptions: number[] = [];
shouldn't we have some default options?

2021-01-07 06:51 UTC, anbalase commented on projects/angular/components/ui-grid/src/components/ui-grid-custom-paginator/ui-grid-custom-paginator.component.ts
> +    public disabled = false;
how is this handled?

2021-01-07 06:52 UTC, anbalase commented on projects/angular/components/ui-grid/src/components/ui-grid-custom-paginator/ui-grid-custom-paginator.module.ts
> +    MatSelectModule,
indentation seems off here

2021-01-07 06:53 UTC, anbalase commented on projects/angular/components/ui-grid/src/components/ui-grid-custom-paginator/ui-grid-custom-paginator.component.scss
> +
```suggestion
```

2021-01-07 06:54 UTC, anbalase commented on projects/angular/components/ui-grid/src/components/ui-grid-custom-paginator/ui-grid-custom-paginator.component.ts
> +            this.currentRangeStart + this.pageSize - 1;
```suggestion
        return (this.currentRangeStart + this.pageSize - 1 > this.length) 
                  ? this.length 
                  : this.currentRangeStart + this.pageSize - 1;
```

2021-01-08 07:27 UTC, anbalase requested changes

2021-01-08 07:27 UTC, anbalase commented on projects/angular/components/ui-grid/src/managers/data-manager.ts
> +export interface GridOptions<T> {
since this is contains flags specific to the whole grid, maybe we should move the declaration from this file.

2021-01-08 07:27 UTC, anbalase commented on projects/angular/components/ui-grid/src/managers/data-manager.ts
> +        this.useAlternateDesign = options?.useAlternateDesign ?? false;
Also, this flag state should also be kept at a grid level, we need to allow for the option of specifying a different value as a grid input case by case.

2021-01-08 07:27 UTC, anbalase commented on projects/angular/components/ui-grid/src/ui-grid.component.html
> +        <ng-container *ngIf="dataManager?.useAlternateDesign; else classicFooter">
so, this would become something like:
```suggestion
        <ng-container *ngIf="useAlternateDesign; else classicFooter">
```

2021-01-08 07:27 UTC, anbalase commented on projects/angular/components/ui-grid/src/components/ui-grid-custom-paginator/ui-grid-custom-paginator.component.ts
> +@Injectable({ providedIn: 'root' })
This does not have to be provided in `root`, pls take a look at how `UiGridIntl` is set up and exported. 
We'll also need to be able to provide it in consumers as an alternate of `MatPaginatorIntl` with specific localization logic.
```suggestion
@Injectable()
```

2021-01-08 07:27 UTC, anbalase commented on projects/angular/components/ui-grid/src/components/ui-grid-custom-paginator/ui-grid-custom-paginator.component.ts
> +export class CustomMatPaginatorIntl extends MatPaginatorIntl {
```suggestion
export class UiMatPaginatorIntl extends MatPaginatorIntl {
```

2021-01-08 07:27 UTC, anbalase commented on projects/angular/components/ui-grid/src/components/ui-grid-custom-paginator/ui-grid-custom-paginator.component.html
> +            <button mat-icon-button
let's reorder the attributes to match conventions.

2021-01-08 07:27 UTC, anbalase commented on projects/angular/components/ui-grid/src/components/ui-grid-custom-paginator/ui-grid-custom-paginator.component.ts
> +
nit:
```suggestion
```

2021-01-08 07:27 UTC, anbalase commented on projects/angular/components/ui-grid/src/components/ui-grid-custom-paginator/ui-grid-custom-paginator.component.ts
> +
nit:
```suggestion
```

2021-01-08 07:27 UTC, anbalase commented on projects/angular/components/ui-grid/src/components/ui-grid-custom-paginator/ui-grid-custom-paginator.component.ts
> +    _formFieldAppearance?: MatFormFieldAppearance;
```suggestion
    private _formFieldAppearance?: MatFormFieldAppearance;
```

2021-01-08 07:27 UTC, anbalase commented on projects/angular/components/ui-grid/src/components/ui-grid-custom-paginator/ui-grid-custom-paginator.component.ts
> +    _intl!: CustomMatPaginatorIntl;
```suggestion
    private _intl!: CustomMatPaginatorIntl;
```

2021-01-12 12:51 UTC, anbalase commented on projects/angular/components/ui-grid/src/ui-grid.component.spec.ts
> +            expect(grid.useAlternateDesign).toBeTrue();
I'd recommend testing the rendered state, instead of verifying a flag value we should check the DOM for a relevant element.

2021-01-12 12:52 UTC, anbalase commented on projects/angular/components/ui-grid/src/ui-grid.component.spec.ts
> +                        it(`should be able to reset on (${e instanceof KeyboardEvent
nit: It looked better before 😄

2021-01-12 12:55 UTC, anbalase commented on projects/angular/components/ui-grid/src/components/ui-grid-custom-paginator/ui-grid-custom-paginator.component.ts
> +            return `Page ${currentPage}`;
Let's add a test for this branch pls.

2021-01-14 11:01 UTC, mhagape commented on projects/angular/components/ui-grid/src/ui-grid.component.html
> +        </ng-container>
You could use a ternary to improve readability.
```suggestion
        <ng-container *ngTemplateOutlet="useAlternateDesign ? alternativeFooter : classicFooter"></ng-container>
```

2021-01-14 11:02 UTC, mhagape commented on projects/angular/components/ui-grid/src/components/ui-grid-custom-paginator/ui-grid-custom-paginator.component.spec.ts
> +            fixture = TestBed.createComponent(TestFixtureComponent);
Don't forget to destroy the `fixture`.

2021-01-18 09:30 UTC, anbalase approved these changes
lgtm
@alexdudescu  pls `git rebase -i 17cd4a7a8623f5f4faa57ef2c3155e4916c17fbd --autosquash` if all good 😃

2021-01-18 10:36 UTC, anbalase approved these changes

2021-01-18 10:44 UTC, merged