🚧feat(grid): update no content template
UiPath/angular-components pull request #124
Opened 2021-03-09 16:15 UTC by robertandreimoldoveanu

2021-03-09 16:52 UTC, CalinaCristian reviewed
Maybe add some tests as well for a grid with noDataMessage passed?

2021-03-09 16:52 UTC, CalinaCristian commented on projects/angular/components/ui-grid/src/ui-grid.component.html
> +         [class.ui-grid-no-content-available]="!header?.searchValue && !(filterManager.activeCount$ | async)"
subscribe only once with a ngLet?

2021-03-09 17:09 UTC, vladjerca commented on projects/angular/components/ui-grid/src/ui-grid.component.html
> +         [class.ui-grid-no-content-available]="!header?.searchValue && !(filterManager.activeCount$ | async)"
`ngLet`? https://github.com/UiPath/angular-components/blob/master/projects/angular/directives/ui-ng-let/src/ui-ng-let.directive.ts

2021-03-10 08:35 UTC, anbalase commented on projects/angular/components/ui-grid/src/ui-grid.component.html
> +         [class.ui-grid-no-content-available]="!header?.searchValue && !(filterManager.activeCount$ | async)"
How are we going to accomplish a different layout for no content (with no filters or search)? It's more than just text alignment, we also need another icon. Maybe we should branch out to a different template based on `useAlternateDesign`?

2021-03-10 08:36 UTC, anbalase commented on projects/angular/components/ui-grid/src/ui-grid.intl.ts
> +    public noDataMessage = (_searchValue?: string, _activeFilters?: number | null) => 'No data is available.';
This will be a breaking change, let's use another one for an alternate message.

2021-03-10 09:11 UTC, robertandreimoldoveanu commented on projects/angular/components/ui-grid/src/ui-grid.component.html
> +         [class.ui-grid-no-content-available]="!header?.searchValue && !(filterManager.activeCount$ | async)"
I was thinking of adding the icon from CSS in Orchestrator (attaching SVG on a pseudo element).
I find that this way the grid is more consistent - it's always displaying text - and also allows room for change depending on the scenario

2021-03-10 14:51 UTC, CalinaCristian submitted a review, later dismissed

2021-03-10 14:53 UTC, anbalase requested changes

2021-03-10 15:20 UTC, anbalase commented on projects/angular/components/ui-grid/src/ui-grid.intl.ts
> +    public noDataMessageAlternative = (_searchValue?: string, _activeFilters?: number | null) => 'No data is available.';
Looks a bit wrong to declare these arguments with leading `_`.
Also, shouldn't we have tests for the grid for this new logic?
```suggestion
    public noDataMessageAlternative = (searchValue?: string, activeFilters?: number | null) => `No data is available ${searchValue ? ` for ${searchValue}${activeFilters? ' for applied filters': ''}`}.`;
```

2021-03-10 15:35 UTC, robertandreimoldoveanu commented on projects/angular/components/ui-grid/src/ui-grid.component.scss
> +                    height: 4 * $ui-grid-row-height;
Might be, but if they have a `pageSize` too big, the centered message will be below the fold and not visible. I think we should ask design.

2021-03-11 11:41 UTC, anbalase approved these changes

2021-03-11 12:50 UTC, merged