fix: a11y grid
UiPath/angular-components pull request #135
Opened 2021-03-19 14:41 UTC by robertandreimoldoveanu

- [x] add cell headers association - assure row headers
- [ ] reveal changes in header when a selection is made
- [ ] others

2021-03-26 08:33 UTC, anbalase requested changes

2021-03-26 08:33 UTC, anbalase commented on projects/angular/components/ui-grid/src/ui-grid.component.spec.ts
> +                it('should render first column cells as row headers', () => {
Let's write more meaningful tests, let's check the following scenarios pls:
3 columns, no primary => should mark the first column as a row header.
3 columns, 2nd & 3rd are primary => should mark only the 1st primary as a row header.

2021-03-26 08:33 UTC, anbalase commented on projects/angular/components/ui-grid/src/ui-grid.component.ts
> +    public isRowHeader(columns?: UiGridColumnDirective<T>[], index?: number) {
When can this be called with no arguments?
```suggestion
    public isRowHeader(columns: UiGridColumnDirective<T>[], index: number) {
```

2021-03-26 08:33 UTC, anbalase commented on projects/angular/components/ui-grid/src/ui-grid.component.html
> +                     [attr.role]="isRowHeader(visibleColumns, index) ? 'rowheader' : 'gridcell'"
I'd recommend not having method calls that set attributes, especially in a *ngFor for each cell...
Let's compose a stream for this added state, starting from visible$ to optimize this.

2021-03-29 07:48 UTC, anbalase requested changes

2021-03-29 07:48 UTC, anbalase commented on projects/angular/components/ui-grid/src/managers/selection-manager.ts
> +    public hasValue$: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(false);
Let's expose this as an Observable with `distictintUntilChanged()`
```suggestion
    private _hasValue$ = new BehaviorSubject<boolean>(false);
    public hasValue$ = this._hasValue$.pipe(distictintUntilChanged());
```

2021-03-29 07:48 UTC, anbalase commented on projects/angular/components/ui-grid/src/ui-grid.component.ts
> +        distinctUntilChanged(),
```suggestion
```

2021-03-29 07:48 UTC, anbalase commented on projects/angular/components/ui-grid/src/ui-grid.component.ts
> +            if (hasSelection && !!this.header?.actionButtons?.length) {
if we have 2 subscriptions then we will announce twice, this should be avoided.

2021-03-29 07:48 UTC, anbalase commented on projects/angular/components/ui-grid/src/body/ui-grid-column.directive.spec.ts
> +            it('should have primary set to false', () => {
why did we change this test? 😄

2021-03-29 07:48 UTC, anbalase commented on projects/angular/components/ui-grid/src/ui-grid.component.spec.ts
> +                    const firstRow = fixture.debugElement.queryAll(By.css('.ui-grid-row'))[0];
```suggestion
                    const firstRow = fixture.debugElement.query(By.css('.ui-grid-row'));
```

2021-03-29 07:48 UTC, anbalase commented on projects/angular/components/ui-grid/src/ui-grid.component.spec.ts
> +                    const firstRow = fixture.debugElement.queryAll(By.css('.ui-grid-row'))[0];
```suggestion
                    const firstRow = fixture.debugElement.query(By.css('.ui-grid-row'));
```

2021-03-29 07:48 UTC, anbalase commented on projects/angular/components/ui-grid/src/ui-grid.component.html
> +         *ngIf="hasSelection$ | async "
There are other places where we can switch to this stream, could we update all the places where `selectionManager.hasValue()` is being used?
```suggestion
         *ngIf="hasSelection$ | async"
```

2021-03-29 10:53 UTC, robertandreimoldoveanu commented on projects/angular/components/ui-grid/src/body/ui-grid-column.directive.spec.ts
> +            it('should have primary set to false', () => {
Before, the primary value was unreactive and the `change$` stream didn't emit when the primary input was changed, thus causing problems with the `ui-grid` tests. I changed how the property behaves and also it's default value, so that's why I changed the test as well.

2021-03-29 11:07 UTC, robertandreimoldoveanu commented on projects/angular/components/ui-grid/src/body/ui-grid-column.directive.ts
> +    public role?: string;
The type-checker throws errors otherwise :( 
It's not a side effect, a map operator that sets the property when rendering the visible columns. So right now, it is always set where we need it to be set. 
It's true not all consumers have it set, though. Perhaps we could add a default value instead of it being optional, but given that it's not used somewhere else, it wouldn't have any benefit. This was added to assure a better accessibility, I don't see how it could be used in other places.
Perhaps we could extend that class and create a new type, would that work better?

2021-03-29 11:13 UTC, anbalase commented on projects/angular/components/ui-grid/src/body/ui-grid-column.directive.ts
> +    public role?: string;
Could we just define a new type and compose a new object where we consume the stream?

2021-03-30 05:18 UTC, anbalase approved these changes

2021-03-30 08:49 UTC, merged