fix(grid): fix hasValue stream
UiPath/angular-components pull request #138
Opened 2021-03-30 15:57 UTC by robertandreimoldoveanu

2021-03-30 15:59 UTC, CalinaCristian approved these changes

2021-03-30 18:23 UTC, anbalase requested changes
The code looks good, let's pls add a test for the scenario that needed this fix.

2021-03-30 18:23 UTC, anbalase commented on projects/angular/components/ui-grid/src/managers/selection-manager.ts
> +        this._hasValue$.next(this.hasValue());
Let's please add a test for this to document it. 
Looking at the code, it's not clear what the underlying issue was.

2021-03-31 11:05 UTC, anbalase approved these changes

2021-03-31 11:50 UTC, merged

2021-03-31 11:50 UTC, CalinaCristian approved these changes