feature/a11y-testing
UiPath/angular-components pull request #157
Opened 2021-05-26 12:34 UTC by robertandreimoldoveanu

2021-05-26 13:15 UTC, anbalase commented on package.json
> +    "jasmine-axe": "^1.0.0",
test conversation

2021-05-28 06:03 UTC, anbalase requested changes
Could we add the same basic test for all components?Let's target next release with this.
Pls don't forget to do the version bump so that it will be ready for next release.

2021-05-31 10:10 UTC, anbalase approved these changes

2021-06-04 11:34 UTC, CalinaCristian approved these changes

2021-06-08 08:49 UTC, merged