feat(grid): expose and change default fetchStrategy
UiPath/angular-components pull request #160
Opened 2021-06-08 13:22 UTC by anbalase

`fetchStrategy?: 'eager' | 'onOpen'`

2021-06-17 09:38 UTC, robertandreimoldoveanu commented on projects/angular/components/ui-grid/src/ui-grid.component.ts
> +            map(areVisible => areVisible.filter(visible => visible).length),
i think `.some` was better as it's more concise, `.filter` and `.length` seem like "workarounds" given that there's a function for that exact purpose. also wouldn't `areVisible.some(Boolean)` achieve the same and be clearer?

2021-06-17 10:17 UTC, anbalase commented on projects/angular/components/ui-grid/src/ui-grid.component.ts
> +            map(areVisible => areVisible.filter(visible => visible).length),
But we need the actual count not a Boolean.

2021-06-17 10:18 UTC, alexdudescu requested changes

2021-06-17 10:18 UTC, alexdudescu commented on projects/playground/.eslintrc.json
> +        }
Since we're not overriding any rules, we should drop this

```suggestion
        }
```

2021-06-17 12:24 UTC, anbalase commented on projects/angular/components/ui-grid/src/ui-grid.intl.ts
> +        `No data is available${searchValue ? ` for ${searchValue}` : ''}${activeFilters ? ' for applied filters' : ''}.`;
but it rendered differently if all were falsy, you'd get `...available .` instead of `...available.`

2021-06-18 10:35 UTC, alexdudescu commented on projects/angular/components/ui-grid/src/ui-grid.component.spec.ts
> +                        `should emit sort event when key '${ev.key}' is pressed ` +
Concatenating strings with `+` will always results in this sort of formatting if the line length would exceed the maximum allowed. If we wish to have everything on one line, we should stick with one string & the according `eslint-disable` rule(s).

2021-06-18 10:54 UTC, anbalase commented on projects/angular/components/ui-grid/src/ui-grid.component.spec.ts
> +                        `should emit sort event when key '${ev.key}' is pressed ` +
or leave it as is, it's more readable this way...

2021-06-18 11:51 UTC, alexdudescu approved these changes
LGTM ✨

2021-06-18 11:51 UTC, merged