feat(grid): add filters empty state input
UiPath/angular-components pull request #212
Opened 2022-02-17 11:53 UTC by CatalinB7

Create optional input `emptyValue` for `UiGridDropdownFilterDirective` in order to clearly count the applied filters of the grid

2022-02-21 09:25 UTC, anbalase commented on projects/angular/components/ui-grid/src/ui-grid.component.html
> +                            <p [class.ui-grid-header-title-filtered]="(column.dropdown?.value != null && column.dropdown?.value?.value !== column.dropdown?.emptyStateValue) ||
```suggestion
                            <p [class.ui-grid-header-title-filtered]="(column.dropdown?.value != null && column.dropdown!.value!.value !== column.dropdown!.emptyStateValue) ||
```

2022-02-21 14:04 UTC, CalinaCristian requested changes
Fix the unit tests, otherwise it seems fine 🚀

2022-02-21 14:04 UTC, CalinaCristian commented on projects/angular/components/ui-grid/src/ui-grid.component.spec.ts
> +                it('should not count applied default filter when there is not empty filter state', () => {
this should (and is) not be the behavior.. you apply the count on default filters every time.
As we spoke, this seems to be a broken setup for this test.

Maybe create a different Fixture component for those specific tests.

2022-02-21 20:02 UTC, CalinaCristian submitted a review, later dismissed

2022-02-21 20:03 UTC, CalinaCristian commented
Don't forget about the chore: bump version commit & tag

2022-02-22 10:17 UTC, alexdudescu approved these changes

2022-02-22 12:06 UTC, alexdudescu approved these changes

2022-02-22 12:13 UTC, merged