feat(suggest): add compact summary support
UiPath/angular-components pull request #240
Opened 2022-07-27 14:22 UTC by anatolie-darii

2022-07-27 14:40 UTC, sergiubologa requested changes
Looks good! Some unit tests and it's good from my side

2022-07-27 14:40 UTC, sergiubologa commented on projects/angular/components/ui-suggest/src/ui-suggest.component.html
> +    <ng-container *ngIf="(!multiple || compact); else chipsTemplate">
Maybe would make sense to extract `(!multiple || compact)` in its own variable in the `*ngLet` above, since it's used 2 times and a suggestive name would make the code easier to read.

2022-07-28 06:33 UTC, anatolie-darii commented on projects/angular/components/ui-suggest/src/ui-suggest.component.html
> +    <ng-container *ngIf="(!multiple || compact); else chipsTemplate">
we should probably do something like refactoring `multiple: boolean` into `multiple: 'chips' | 'compact'` but that would involve more changes and I wanna keep this PR small and safe

2022-07-28 08:21 UTC, sergiubologa submitted a review, later dismissed

2022-07-28 08:48 UTC, anbalase commented on projects/angular/components/ui-suggest/src/ui-suggest.component.ts
> +                .join(',')
could we extract and reuse from [here](https://github.com/UiPath/angular-components/blob/3fb40552de32cd71d6101e4d7aa0208af89b5740/projects/angular/components/ui-suggest/src/ui-suggest.component.ts#L312)? 
```suggestion
                .join(', ')
```

2022-07-28 09:00 UTC, anatolie-darii commented on projects/angular/components/ui-suggest/src/ui-suggest.component.ts
> +                .join(',')
done!

2022-07-28 09:34 UTC, anbalase approved these changes

2022-07-28 10:13 UTC, sergiubologa approved these changes

2022-07-28 12:02 UTC, merged