feat(grid): reset search, filters and sorting on action
UiPath/angular-components pull request #285
Opened 2022-11-18 23:22 UTC by AlexandruCGhimisi

* clear search, filters and sorting on action and emit an event to notify user, so they can process the operation

2022-11-19 00:02 UTC, CalinaCristian commented on projects/playground/src/app/pages/grid/component/grid.component.html
> +        <ui-header-button type="inline">
this should be an input, not always display it

2022-11-19 00:06 UTC, CalinaCristian commented on projects/playground/src/app/pages/grid/component/grid.component.ts
> +        this._grid.refresh.subscribe(_ =>
this should be under a `takeUntil(this._destroyed$)`.. Also, why adding this logic here? Shouldn't it be done in `reset()` method above?

2022-11-19 00:08 UTC, CalinaCristian reviewed
You should add tests for this scenario as well.

2022-11-21 15:19 UTC, anbalase requested changes

2022-11-21 15:19 UTC, anbalase commented on projects/angular/components/ui-grid/src/ui-grid.component.ts
> +    clearAll() {
would be nice if consumers can override this behavior, it should also return a stream so you can compose reactive logic to it.
e.g. 
```ts
// [clearAll]=() { return this._consumerService.resetStorage(); }

@Input()
clearAll: (this)=> Observable<boolean>  = ...

// ...
clearButtonClick() {
    this.clearAll().pipe(
    tap(()=>this.filtersCleared.emit()),
).subscribe();
}

```

2022-11-21 15:19 UTC, anbalase commented on projects/angular/components/ui-grid/src/ui-grid.component.ts
> +    clearAll() {
how should a consumer hook this up? 
should we expose a standard inline clear button that invokes this?
Y - pls add
N - let's add a comment with for recommended usage.

2022-11-21 16:54 UTC, AlexandruCGhimisi commented on projects/angular/components/ui-grid/src/ui-grid.component.ts
> +    clearAll() {
On the long run it would be nice to have a standard button. This requires design validation, so I would skip that for when we really need this functionality. For now, we only need a way to programmatically clear filters.

2022-11-21 22:21 UTC, AlexandruCGhimisi commented on projects/angular/components/ui-grid/src/ui-grid.component.ts
> +    clearAll() {
Nice idea. I'll do that

2022-11-23 12:06 UTC, anbalase approved these changes

2022-11-23 12:34 UTC, anbalase approved these changes

2022-11-23 13:02 UTC, merged