Feat/tree select
UiPath/angular-components pull request #289
Opened 2022-11-23 16:48 UTC by robertandreimoldoveanu

2022-11-25 10:38 UTC, alexdudescu commented on projects/angular/components/ui-tree-select/src/ui-tree-item/ui-tree-item.component.html
> + -->
💬

2022-11-25 10:39 UTC, alexdudescu commented on projects/angular/components/ui-tree-select/src/ui-tree-select.component.scss
> +// }
💬

2022-11-25 10:44 UTC, alexdudescu commented on projects/angular/components/ui-tree-select/src/ui-tree-select.component.scss
> +      padding-left: max(0, calc($padding * ($level)));
Can you ever have negative levels? As for the padding I think you there's only negative margin.
```suggestion
      padding-left: calc($padding * ($level));
```

2022-11-25 10:44 UTC, alexdudescu commented on projects/playground/src/app/pages/tree-select/tree-select.page.ts
> +// }
💬

2022-11-25 10:46 UTC, anbalase commented on projects/angular/components/ui-tree-select/src/models/tree.ts
> +export interface FlatNode {
would love to have this interface generic for data, by default set to any.

2022-11-25 10:48 UTC, anbalase commented on projects/angular/components/ui-tree-select/src/ui-tree-item/ui-tree-item.component.html
> +            class="toggle-button"
`type="button"`

2022-11-25 10:49 UTC, anbalase commented on projects/angular/components/ui-tree-select/src/ui-tree-item/ui-tree-item.component.html
> +        <span>
is this needed?

2022-11-25 10:50 UTC, anbalase commented on projects/angular/components/ui-tree-select/src/ui-tree-select.component.html
> +                <ng-content select="[noDataMessage]"></ng-content>
👍

2022-11-25 10:51 UTC, anbalase commented on projects/angular/components/ui-tree-select/src/ui-tree-select.component.scss
> +  border: 2px solid cyan;
ups

2022-11-25 10:52 UTC, anbalase commented on projects/angular/components/ui-tree-select/src/ui-tree-select.component.scss
> +  @include perLevelPadding(0, 32px);
https://sass-lang.com/documentation/at-rules/control/for

2022-11-25 10:53 UTC, anbalase commented on projects/angular/components/ui-tree-select/src/models/tree.ts
> +export interface Node {
consider a more specific naming for interfaces we don't want to confuse these

2022-11-25 10:54 UTC, anbalase commented on projects/angular/components/ui-tree-select/src/models/tree.ts
> +    key: string;
key should support both `string | number`

2022-11-25 10:56 UTC, anbalase commented on projects/angular/components/ui-tree-select/src/ui-tree-select.component.ts
> +    private keyManager?: FocusKeyManager<UiTreeItemComponent>;
```suggestion
    private _keyManager?: FocusKeyManager<UiTreeItemComponent>;
```

2022-11-25 10:57 UTC, anbalase requested changes
pls add decent coverage

2022-11-25 19:44 UTC, robertandreimoldoveanu commented on projects/angular/components/ui-tree-select/src/ui-tree-select.component.scss
> +      padding-left: max(0, calc($padding * ($level)));
fair point.
took note of the feedback and moved the styles to the playground.

2022-11-25 19:44 UTC, robertandreimoldoveanu commented on projects/angular/components/ui-tree-select/src/ui-tree-item/ui-tree-item.component.html
> +        <span>
nope it wasn't, removed it.
thanks

2022-11-25 19:46 UTC, robertandreimoldoveanu commented on projects/angular/components/ui-tree-select/src/ui-tree-select.component.scss
> +  @include perLevelPadding(0, 32px);
thanks for the tip, was thinking that we might need a for loop there 😄 
moved the styles to the playground tho, as I feel these are consumer decisions to be made.
could we export this mixin to the consumer? so they can just call it with their own padding values if needed

2022-11-25 19:47 UTC, robertandreimoldoveanu commented on projects/angular/components/ui-tree-select/src/models/tree.ts
> +export interface Node {
changed to `IFlatNodeObject` 'cause it's an interface the consumer shouldn't need, and `ITreeNode` which is self explanatory and seems better formulated

2022-11-25 19:50 UTC, robertandreimoldoveanu commented on projects/angular/components/ui-tree-select/src/models/tree.ts
> +    key: string;
do we want that though? consumers with IDs could `toString` and have certainty of type
thinking that we've had situations where we wanted to support both and were problematic 😓

2022-12-02 13:21 UTC, anbalase commented on projects/angular/components/ui-tree-select/src/models/tree.ts
> +    key: string;
Well, you're just pushing this issue to consumers. 
But, since this won't be used as a CVA and output doesn't matter, I guess it's fine to keep these as strings here.

2022-12-02 19:28 UTC, CalinaCristian commented on projects/angular/components/ui-tree-select/src/models/tree.models.ts
> +}
can't we extract the common `key`, `name` and `data` to an interface and extend it in both of those interfaces?

2022-12-05 08:38 UTC, anbalase requested changes

2022-12-05 10:58 UTC, anbalase commented on projects/angular/components/ui-tree-select/src/ui-tree-item/ui-tree-item.component.html
> +  <mat-list-item (click)="click()"
pls check a11y wise how this behaves without a mat-list as a direct parent

2022-12-05 10:58 UTC, anbalase commented on projects/angular/components/ui-tree-select/src/ui-tree-select.component.html
> +        <mat-list class="tree-container">
```suggestion
        <mat-list class="tree-container" role="list">
```

2022-12-05 10:59 UTC, anbalase commented on projects/angular/components/ui-tree-select/src/ui-tree-select.component.html
> +                                 itemSize="26">
should this be overridable based on the template used?

2022-12-06 17:29 UTC, anbalase commented on projects/angular/components/ui-tree-select/src/ui-tree-select.component.ts
> +    @HostBinding('style.--ui-tree-select-item-padding')
🤟

2022-12-07 09:10 UTC, CalinaCristian commented on projects/angular/components/ui-tree-select/src/ui-tree-select.component.ts
> +    @HostBinding('style.--ui-tree-select-item-padding')
😮

2022-12-13 07:36 UTC, anbalase commented on projects/angular/components/ui-tree-select/src/ui-tree-select.component.html
> +                    <ng-template *ngIf="itemTemplate"
It's very powerful to just allow the consumer to specify a template. 
Shouldn't we have a default, still? 
Seems a bit of an overhead that each consumer needs to implement this if you just need to render the text of the node.

2022-12-13 07:36 UTC, anbalase commented on projects/angular/components/ui-tree-select/src/ui-tree-select.component.ts
> +    currentSelectedNode: IFlatNodeObject | null = null;
how will this work for multi-select?
are going to rewrite it for that scenario?

2022-12-13 07:36 UTC, anbalase commented on projects/angular/components/ui-tree-select/src/ui-tree-select.component.ts
> +    currentSelectedNode: IFlatNodeObject | null = null;
why not have a set of selected nodes?

2022-12-13 07:36 UTC, anbalase commented on projects/angular/components/ui-tree-select/src/ui-tree-select.component.ts
> +    currentSelectedNode: IFlatNodeObject | null = null;
do we care to hydrate the selection from the consumer?

2022-12-13 07:40 UTC, robertandreimoldoveanu commented on package.json
>      "test:watch": "ng test",
no
`test` is just a shortcut to the existing `test:watch` command. the `watch` is default
now it can be ran with `npm test` instead of `npm run test:watch`

2022-12-13 07:46 UTC, robertandreimoldoveanu commented on projects/angular/components/ui-tree-select/src/ui-tree-select.component.html
> +                    <ng-template *ngIf="itemTemplate"
I think that supporting both right now adds some convoluted logic in the template. i'd rather we have simplicity than turn into another `ui-suggest`. 

the most basic use would be:
```
<ng-template *ngIf="itemTemplate" let-node="node">
     {{node.name}}
</ng-template>
```

we can hardly call that overhead. on the other hand, implementing a default and asking the consumer to provide an `Intl` service is more overhead imho than this

2022-12-13 07:48 UTC, robertandreimoldoveanu commented on projects/angular/components/ui-tree-select/src/ui-tree-select.component.ts
> +    currentSelectedNode: IFlatNodeObject | null = null;
i think multiselect would be a v2 feature. surely needs to exist, but not right now
i missed hydrating the selection, will add

2022-12-13 08:57 UTC, anbalase commented on projects/angular/components/ui-tree-select/src/ui-tree-select.intl.ts
> +export class UiTreeSelectIntl implements OnDestroy {
drop

2022-12-13 10:33 UTC, anbalase requested changes

2022-12-13 10:33 UTC, anbalase commented on projects/angular/components/ui-tree-select/src/ui-tree-select.component.ts
> +    itemTemplate!: any;
```suggestion
    itemTemplate?: TemplateRef<any>;
```

2022-12-13 19:35 UTC, robertandreimoldoveanu commented
the `check-public-exports` script failed due to:

![image](https://user-images.githubusercontent.com/11781688/207427910-24fa95e2-0abf-4929-9e8c-f47ec4b5fa2b.png)

the job running this script gets skipped under some conditions. I expect during the Angular 14 upgrade it became deprecated but still somehow got skipped

2022-12-14 16:26 UTC, anbalase commented on projects/playground/src/app/pages/tree-select/tree-select.module.ts
> +export class TreeSelectModue { }
do we need this?

2022-12-14 16:28 UTC, anbalase commented on projects/angular/components/ui-tree-select/src/ui-tree-select.component.ts
> +    set initialSelection(value: string[]) {
```suggestion
    set initialSelection(value: string[] | null) {
```

2022-12-14 17:10 UTC, anbalase approved these changes

2022-12-16 08:27 UTC, anbalase approved these changes

2022-12-16 08:45 UTC, merged