Fix: display correctly column sort icon
UiPath/angular-components pull request #312
Opened 2023-03-01 07:59 UTC by CatalinB7

2023-03-01 08:56 UTC, CalinaCristian approved these changes
have you verified that it still looks ok with both sortable and description (are they aligned properly now that the DOM structure changed)?

2023-03-01 09:30 UTC, anbalase requested changes
a tooltip would be needed on focus as well

2023-03-01 16:11 UTC, caleniuc commented
On blur on a column with the info icon displayed, right after the big tooltip is hidden, it seems it shows also the `p` tag's tooltip only for a very short period.

2023-03-02 09:36 UTC, CatalinB7 commented on projects/angular/components/ui-grid/src/ui-grid.component.html
> +                         (focusout)="focusedColumnHeader = false; columnTooltip.hide()"
```suggestion
                         (focusout)="focusedColumnHeader = false; columnTooltip.hide(0)"
```

2023-03-02 09:42 UTC, CatalinB7 commented on projects/angular/components/ui-grid/src/ui-grid.component.html
> +                         (focusout)="focusedColumnHeader = false; columnTooltip.hide()"
keyboard focus only

2023-03-02 12:57 UTC, CatalinB7 commented on projects/angular/components/ui-grid/src/ui-grid.component.ts
> +        }, 0);
focus-visible appears for a short moment on mouse clicks as well :(

2023-03-02 20:45 UTC, robertandreimoldoveanu requested changes
the solutions is ingenious but convoluted and brings no value as all a11y criteria are met w/o it. i can't see any valuable use for this other than a tiny nice to have. imho it's code bloat. 

i would've proposed adding some tests but that would make it even worse.

can we revisit this?

2023-03-03 00:09 UTC, CalinaCristian commented on projects/angular/components/ui-grid/src/ui-grid.component.ts
> +            const styles = window.getComputedStyle(event.target as HTMLElement, ':before');
I agree with @robertandreimoldoveanu. It seems like the voiceover utility reads the whole tooltip when you focus via keyboard (both description and title). You don't need to show the tooltip in this scenario.

Also, this `getComputedStyle` method is known to be slow.
You can read more about it [here](https://gist.github.com/paulirish/5d52fb081b3570c81e3a#calling-getcomputedstyle)

> Calling getComputedStyle()
window.getComputedStyle() will typically force style recalc.
window.getComputedStyle() will often force layout, as well.

2023-03-03 00:12 UTC, CalinaCristian commented on projects/angular/components/ui-grid/src/ui-grid.component.ts
> +            const styles = window.getComputedStyle(event.target as HTMLElement, ':before');
<img width="862" alt="Screenshot 2023-03-02 at 4 11 54 PM" src="https://user-images.githubusercontent.com/9513641/222596917-2d303c8c-d0ef-48d9-8d59-7342e8c77329.png">

2023-03-03 12:52 UTC, CatalinB7 commented
it is a requirement for the information to be available to someone who only uses the keyboard => a tooltip must be displayed to show the column description => 2 possibilities:
1. make the icon focusable 
2. display tooltip with the concatenation of column title and description.

Will try to implement the 2nd.

2023-03-03 15:22 UTC, robertandreimoldoveanu approved these changes
still unsure about the worth of this but at least the code looks manageable and is cleaner

2023-03-06 07:18 UTC, anbalase reviewed
@CatalinB7 pls specify the a11y criteria for clarity. 
How does this logic behave for the screen-reader when focusing a column header?

2023-03-07 21:33 UTC, CatalinB7 commented
https://sarahmhigley.com/writing/tooltips-in-wcag-21/
"Tooltips must be discoverable and readable with a mouse, other pointer devices, keyboard, screen reader, zoom software, and any other assistive technology."

> How does this logic behave for the screen-reader when focusing a column header?

https://user-images.githubusercontent.com/87014385/223557586-e2c65f54-40c6-4f19-8d00-a8fd9c198f8a.mp4

2023-03-08 09:48 UTC, anbalase approved these changes

2023-03-08 10:28 UTC, alexdudescu approved these changes

2023-03-08 10:28 UTC, merged