feat(suggest): adding cdk layout for dropdown
UiPath/angular-components pull request #315
Opened 2023-03-10 08:56 UTC by ZoicanDenisUi

**Description**
If we place the `ui-suggest` component inside a container that has `overflow:hidden`, the user cannot see the options and cannot interact with them. To solve this problem, I used `cdk layout` to show the options that will be placed over all elements.

I added a new Input property that will forcefully place the dropdown over the component.

**Breaking change**
A problem that users may encounter is that the scss that was applied on the elements is not visible anymore because the dropdown was moved outside the component and class names were changed.  To solve this problem, the scss queries must be changed.

2023-03-10 09:21 UTC, sergiubologa requested changes

2023-03-10 09:21 UTC, sergiubologa commented on projects/angular/components/ui-suggest/src/ui-suggest.component.html
> +         [class.suggest-dropdown-item-list-container-expanded-inline]="expandInline"
```suggestion
         [class.ui-suggest-dropdown-item-list-container-expanded-inline]="expandInline"
```

2023-03-10 09:21 UTC, sergiubologa commented on projects/angular/components/ui-suggest/src/ui-suggest.component.spec.ts
> +                component.multiple = true;
why are these needed?

2023-03-10 09:21 UTC, sergiubologa commented on projects/angular/components/ui-suggest/src/ui-suggest.component.spec.ts
> +            component.multiple = true;
is this really needed?

2023-03-10 09:21 UTC, sergiubologa commented on projects/angular/components/ui-suggest/src/ui-suggest.component.ts
> +            };
please move this into a private function with a descriptive name (e.g.: `_adjustDropdownPositionWhenUsingFormControl()`). Also, please add a comment explaining why this adjustment is needed.

2023-03-10 09:21 UTC, sergiubologa commented on projects/angular/components/ui-suggest/src/ui-suggest.component.html
> +    <div [style.width]="suggestContainerWidth+'px'"
```suggestion
    <div [style.width.px]="suggestContainerWidth"
```

2023-03-10 10:00 UTC, sergiubologa requested changes
There's also a small difference between the master and your branch, in the way the dropdown/overlay is displayed when opened, in relation to the parent control. For example, for the first item in the playground (Single select suggest) this is how it's opened on the master branch
![image](https://user-images.githubusercontent.com/10432669/224285896-a2cf4843-96c7-4b20-974f-ea944cb2c9cf.png)
and this is how it's opened on your branch:
![image](https://user-images.githubusercontent.com/10432669/224286116-a6466549-b26f-4654-b687-078af9a3e72c.png)

Notice that on the master the overlay opens up over the parent control, covering it. On your branch, it opens up under the parent control.

2023-03-10 10:41 UTC, ZoicanDenisUi commented on projects/angular/components/ui-suggest/src/ui-suggest.component.html
> +         [class.suggest-dropdown-item-list-container-expanded-inline]="expandInline"
Changed it.

2023-03-10 10:43 UTC, ZoicanDenisUi commented on projects/angular/components/ui-suggest/src/ui-suggest.component.spec.ts
> +            component.multiple = true;
In the old implementation, the test would see the input from the dropdown that would have a height equal to zero. To solve this problem, by setting this property, an input would be rendered in the component and the test will check what it needs.

2023-03-10 10:43 UTC, ZoicanDenisUi commented on projects/angular/components/ui-suggest/src/ui-suggest.component.ts
> +            };
Refactored the code and moved this logic inside a function.

2023-03-10 10:44 UTC, ZoicanDenisUi commented on projects/angular/components/ui-suggest/src/ui-suggest.component.html
> +    <div [style.width]="suggestContainerWidth+'px'"
Changed it

2023-03-13 06:57 UTC, sergiubologa requested changes
When displayed above and over the parent it's not properly aligned:
![image](https://user-images.githubusercontent.com/10432669/224628711-2741bcc3-3465-41ae-aee9-1d57c206ed96.png)

2023-03-13 06:57 UTC, sergiubologa commented on projects/angular/components/ui-suggest/src/ui-suggest.component.ts
> +            this.dropdownPosition = [this.direction === 'up' ? this.upPosition : this.downPosition];
you should call here the `_initDropdownPositions` function

2023-03-13 06:57 UTC, sergiubologa commented on projects/angular/components/ui-suggest/src/ui-suggest.component.ts
> +    forceOriginDropdownPosition = false;
```suggestion
    forceDisplayDropdownOverInput = false;
```

2023-03-13 06:57 UTC, sergiubologa commented on projects/angular/components/ui-suggest/src/ui-suggest.animations.ts
> +        ),
👍 I agree, it looks better without the close transition.

2023-03-13 07:08 UTC, sergiubologa commented
There's another use case that needs to be considered: `ui-suggest` is also used in the `ui-grid`, for filtering. This is how it looks now:
![image](https://user-images.githubusercontent.com/10432669/224631231-10609d83-9bff-446a-ba88-edeb76b077da.png)
this is how it looks on master:
![image](https://user-images.githubusercontent.com/10432669/224631309-b036c1e8-303f-4034-bcfc-e686c99040a3.png)

2023-03-13 07:46 UTC, sergiubologa requested changes

2023-03-13 07:46 UTC, sergiubologa commented on projects/angular/components/ui-suggest/src/ui-suggest.component.ts
> +        }
You can extract this into a private function `_setDropdownOffset`

2023-03-13 07:46 UTC, sergiubologa commented on projects/angular/components/ui-suggest/src/ui-suggest.component.ts
> +        }
Also, this one can be extracted into a private function `_setDropdownOrigin`

2023-03-13 09:15 UTC, ZoicanDenisUi commented on projects/angular/components/ui-suggest/src/ui-suggest.component.ts
> +        }
Changed it

2023-03-13 09:15 UTC, ZoicanDenisUi commented on projects/angular/components/ui-suggest/src/ui-suggest.component.ts
> +        }
Changed it

2023-03-13 09:43 UTC, sergiubologa requested changes

2023-03-13 09:43 UTC, sergiubologa commented on projects/angular/components/ui-suggest/src/ui-suggest.component.ts
> +        if (!this.expandInline) { this._suggestContainerOberserver.unobserve(this.suggestContainer.nativeElement); }
I think the check should be like this
```suggestion
        if (!this.suggestContainer) { this._suggestContainerOberserver.unobserve(this.suggestContainer.nativeElement); }
```

2023-03-13 09:43 UTC, sergiubologa commented on projects/angular/components/ui-suggest/src/ui-suggest.component.ts
>              : [this.downPosition];
```suggestion
        this.dropdownPosition = [this.direction && this.direction === 'up' ? this.upPosition : this.downPosition];
```

2023-03-13 09:43 UTC, sergiubologa commented on projects/angular/components/ui-suggest/src/ui-suggest.component.scss
> +            }
This is causing this alignment issue:
![image](https://user-images.githubusercontent.com/10432669/224663333-394f249c-3edb-404c-8252-03838c9bd13f.png)

2023-03-13 09:43 UTC, sergiubologa commented on projects/angular/components/ui-suggest/src/ui-suggest.component.scss
> +            }
Not sure if this `display: block` is the problem, but there is an issue with the new styles

2023-03-13 13:46 UTC, ZoicanDenisUi commented on projects/angular/components/ui-suggest/src/ui-suggest.component.scss
> +            }
Changed scss

2023-03-13 13:46 UTC, ZoicanDenisUi commented on projects/angular/components/ui-suggest/src/ui-suggest.component.ts
>              : [this.downPosition];
Changed it

2023-03-13 13:46 UTC, ZoicanDenisUi commented on projects/angular/components/ui-suggest/src/ui-suggest.component.ts
> +        if (!this.expandInline) { this._suggestContainerOberserver.unobserve(this.suggestContainer.nativeElement); }
I removed this condition because `suggestContainer` will never be null because is the root element. I refactored the code and added the codition `!this.isExpandInline` because we need to do this just in this case

2023-03-13 13:46 UTC, ZoicanDenisUi commented on projects/angular/components/ui-suggest/src/ui-suggest.component.ts
> +    forceOriginDropdownPosition = false;
Changed it.

2023-03-13 13:46 UTC, ZoicanDenisUi commented on projects/angular/components/ui-suggest/src/ui-suggest.component.ts
> +            this.dropdownPosition = [this.direction === 'up' ? this.upPosition : this.downPosition];
The `_initDropdownPositions`  will init the positions that will be used in this logic (this.upDirection and this.downPosition). If we call this function again here, the variables will be initialized with the same values. I changed the code and refactored a little for a better understanding.

2023-03-13 14:28 UTC, sergiubologa commented
One more issue with the placeholder styling:
![image](https://user-images.githubusercontent.com/10432669/224731399-54b594b0-ad1d-42ce-95d8-1a2054e55670.png)

2023-03-13 14:30 UTC, sergiubologa commented
Also, the 2 bottom examples in the playground page don't show the list of elements when first opened:
![image](https://user-images.githubusercontent.com/10432669/224731799-d3173d4b-6062-48f6-8e18-1721b51c4abb.png)

if I close the dropdown and open it up again it loads them.

2023-03-14 10:29 UTC, sergiubologa commented on projects/angular/components/ui-suggest/src/ui-suggest.component.ts
> +                delay(0),
Why is this needed? If we move the delay above isn't it enough? What if you use `observeOn(asyncScheduler)`?

2023-03-14 12:38 UTC, sergiubologa commented on projects/angular/components/ui-suggest/src/ui-suggest.component.ts
> +                delay(0),
fixed it by using `observeOn(animationFrameScheduler),`

2023-03-15 10:01 UTC, sergiubologa approved these changes

2023-03-16 12:46 UTC, sergiubologa approved these changes

2023-03-16 12:57 UTC, anbalase approved these changes
code looks fine, breaking changes are manageable. pls bump minor and try to state the changes.
cc: @CalinaCristian for apollo overrides

2023-03-16 13:09 UTC, sergiubologa approved these changes

2023-03-16 13:12 UTC, merged