Feat(grid): add radio button selection
UiPath/angular-components pull request #356
Opened 2023-05-24 12:26 UTC by CatalinB7

TODO: 
- [x] add tests

2023-05-24 19:30 UTC, CatalinB7 commented on projects/angular/components/ui-grid/src/ui-grid.component.html
> +                <mat-radio-button></mat-radio-button>
it should 👍

2023-05-26 06:45 UTC, anbalase requested changes

2023-05-26 06:45 UTC, anbalase commented on projects/angular/components/ui-grid/src/ui-grid.component.html
> +                <mat-radio-button (change)="rowSelected(row)"></mat-radio-button>
see checkbox state logic binding to selection manager.
see disabled state
see tooltips

add tests for all of the above

2023-05-29 03:59 UTC, anbalase commented on projects/angular/components/ui-grid/src/ui-grid.component.html
> +            <ng-container *ngLet="disableSelectionByEntry(row) as disabledReason">
can I have both on?

2023-05-29 07:16 UTC, CatalinB7 commented on projects/angular/components/ui-grid/src/ui-grid.component.html
> +            <ng-container *ngLet="disableSelectionByEntry(row) as disabledReason">
nope, solved

2023-05-29 09:36 UTC, caleniuc submitted a review, later dismissed

2023-05-29 09:57 UTC, alexdudescu approved these changes

2023-05-29 10:06 UTC, merged