feat(file-picker): create component
UiPath/angular-components pull request #361
Opened 2023-05-31 16:20 UTC by ioanajoj

Create file picker component based on [component in DU App](https://github.com/UiPath/DU-App/tree/master/src/frontend/libs/shared/ui/src/lib/components/file-upload)

2023-06-09 15:50 UTC, sergiubologa requested changes

2023-06-09 15:50 UTC, sergiubologa commented on projects/angular/utilities/src/array/sort.ts
> +    });
some tests would be useful for this

2023-06-09 15:50 UTC, sergiubologa commented on package.json
> +    "@ngneat/spectator": "^12.0.1",
this is used only for tests, right? If so we should move it in the devDependencies

2023-06-09 15:50 UTC, sergiubologa commented on package.json
> +    "@ngrx/component": "14.3.2",
we should add this also to the peerDependencies here: https://github.com/UiPath/angular-components/blob/4048b3879ec5704e81ab87e083751de90b2b2f6c/projects/angular/package.json#L30

2023-06-10 03:26 UTC, CalinaCristian commented on projects/angular/components/ui-file-picker/src/file-drop-zone/file-drop-zone.service.ts
> +}
as long as the service is provided within the component module or providers, I think we should be fine. It's only an issue when the component depends on services injected by the consume.

2023-06-14 13:57 UTC, ioanajoj commented on projects/angular/components/ui-file-picker/src/ui-file-picker.module.ts
> +import { FileSizePipe } from 'projects/angular/components/ui-file-picker/src/file-size/file-size.pipe';
that was the default when automatically importing, changed

2023-06-14 13:59 UTC, ioanajoj commented on package.json
> +    "@ngrx/component": "14.3.2",
done

2023-06-14 14:00 UTC, ioanajoj commented on package.json
> +    "@ngneat/spectator": "^12.0.1",
done

2023-06-14 14:00 UTC, ioanajoj commented on projects/angular/utilities/src/array/sort.ts
> +    });
done

2023-06-16 14:23 UTC, ioanajoj commented on projects/angular/components/ui-file-picker/src/file-drop-zone/file-drop-zone.service.ts
> +}
provided the service in the file-drop-zone component so that multiple instances of the file picker can be used independently on the same page

2023-06-20 21:18 UTC, CalinaCristian reviewed
Nice work ! I see the pipeline is failing and left some comments.
Once everything is addressed, I'll ✅

2023-06-20 21:18 UTC, CalinaCristian commented on projects/angular/components/ui-file-picker/src/file-drop-zone/file-drop-zone.component.ts
> +        if (!this._accept.length) {
can `_accept` be undefined? In case it can, this should be `this._accept?.length`

2023-06-20 21:18 UTC, CalinaCristian commented on projects/angular/components/ui-file-picker/src/file-drop-zone/file-reader.service.ts
> +        )
would `take` or `takeUntil` be needed here?

2023-06-20 21:18 UTC, CalinaCristian commented on projects/angular/components/ui-file-picker/src/file-drop-zone/file-reader.service.ts
> +            (entry as FileSystemFileEntry).file(f => {
why is it defined as a `FileSystemEntry` in the function but you cast it to `FileSystemFileEntry` here?

2023-06-20 21:18 UTC, CalinaCristian commented on projects/angular/components/ui-file-picker/src/file-drop-zone/file-reader.service.ts
> +            map(filesMatrix => flatten(filesMatrix)),
do you need any `take` or `takeUntil` here?

2023-06-20 21:18 UTC, CalinaCristian commented on projects/angular/components/ui-file-picker/src/file-size/file-size.pipe.spec.ts
> +import { FileSizePipe as SuT } from './file-size.pipe';
what does SuT stand for?

2023-06-20 21:18 UTC, CalinaCristian commented on projects/angular/components/ui-file-picker/src/ui-file-picker.component.html
> +<ng-container *ngrxLet="{
we already have `*ngLet`, is it different?

2023-06-21 12:04 UTC, sergiubologa commented on projects/angular/components/ui-file-picker/src/ui-file-picker.component.html
> +<ng-container *ngrxLet="{
yes, we'll eventually want to move away from `*ngLet` in favor of `*ngrxLet` because of these [advantages](https://v11.ngrx.io/guide/component/let#comparison-with-async-pipe). The same goes for the `ngrxPush`.

2023-06-22 13:19 UTC, ioanajoj commented on projects/angular/components/ui-file-picker/src/file-drop-zone/file-reader.service.ts
> +    getFiles$() {
we are using spectator with jest where it is easier to mock methods than properties, converted to getter

2023-06-22 13:22 UTC, ioanajoj commented on projects/angular/components/ui-file-picker/src/file-drop-zone/file-reader.service.ts
> +    getError$() {
converted to getter

2023-06-22 13:22 UTC, ioanajoj commented on projects/angular/components/ui-file-picker/src/file-drop-zone/file-drop-zone.component.ts
> +    }
move to setter 👍

2023-06-22 13:23 UTC, ioanajoj commented on projects/angular/components/ui-file-picker/src/file-drop-zone/file-drop-zone.component.ts
> +        if (!this._accept.length) {
_accept is defined to empty list by default

2023-06-22 13:23 UTC, ioanajoj commented on projects/angular/components/ui-file-picker/src/file-drop-zone/file-reader.service.ts
> +        )
forkJoin will only emit once, so no need for take, but added takeUntil since the service is now provided in the component

2023-06-22 13:47 UTC, ioanajoj commented on projects/angular/components/ui-file-picker/src/file-drop-zone/file-reader.service.ts
> +            (entry as FileSystemFileEntry).file(f => {
changed the function parameter to be a FileSystemFileEntry since here we are sure it is a file and not a directory

2023-06-22 13:47 UTC, ioanajoj commented on projects/angular/components/ui-file-picker/src/file-drop-zone/file-reader.service.ts
> +            map(filesMatrix => flatten(filesMatrix)),
same as above

2023-06-22 13:47 UTC, ioanajoj commented on projects/angular/components/ui-file-picker/src/file-drop-zone/file-reader.service.ts
> +            map(filesMatrix => flatten(filesMatrix)),
added takeUntil

2023-06-22 13:48 UTC, ioanajoj commented on projects/angular/components/ui-file-picker/src/file-size/file-size.pipe.spec.ts
> +import { FileSizePipe as SuT } from './file-size.pipe';
System under test, sometimes it improves readability 😄

2023-06-22 14:10 UTC, ioanajoj commented on projects/angular/components/ui-file-picker/src/file-drop-zone/file-drop-zone.component.html
> +       aria-hidden="true"
When used inside the file picker, the icon button is the actionable item, focusing it will read `Click to upload or drag and drop` and pressing space or enter will open the browser file picker. I now added a new input for the dropzone disableAria to also support the default focus on the input in case the dropzone is used as a standalone component.

2023-06-22 14:11 UTC, ioanajoj commented on projects/angular/components/ui-file-picker/src/_ui-file-picker.theme.scss
> +                border-top: 1px solid $border-color;
moved width and style

2023-06-22 14:13 UTC, ioanajoj commented
@sergiubologa 
> Some issues/suggestions:
> 
> 1. `Delete all` button is not properly aligned
>    ![image](https://user-images.githubusercontent.com/10432669/247534505-43687b71-b19d-4759-a9c1-6d984193213a.png)
> 2. Would be useful to have more use cases showcased in the sandbox. For example, using only the dropzone component, having the component inside a container with max width and height, using `accept` input, other inputs as well, etc
> 3. I can see you also expose the `file-size` pipe. Some usages for that would be also useful. Although, I think that one should be moved to the pipes folder.

1. I believe it will be when used together with apollo
2. added more usecases in playground

2023-06-24 05:31 UTC, sergiubologa submitted a review, later dismissed

2023-07-31 13:13 UTC, anbalase commented
needs a rebase. other than that, what's missing?

2023-08-07 07:22 UTC, sergiubologa commented
> needs a rebase. other than that, what's missing?

@anbalase made the rebase and small improvements. It can be merged if also @CalinaCristian is ok with it.

2023-08-10 17:52 UTC, CalinaCristian reviewed
Functionality wise it looks good, design wise it's not [per apollo spec](https://www.figma.com/file/Jpv4U4Jcyd8uCbQt5RlZ1K/File-picker-component?type=design&node-id=1223-48089&mode=design&t=lrb5kK4G25CWxzmP-0). 

You can merge this in and we'll probably pick up the work of apollofying after 23.10.

2023-08-10 18:50 UTC, sergiubologa commented
> Functionality wise it looks good, design wise it's not [per apollo spec](https://www.figma.com/file/Jpv4U4Jcyd8uCbQt5RlZ1K/File-picker-component?type=design&node-id=1223-48089&mode=design&t=lrb5kK4G25CWxzmP-0). 
> 
> 
> 
> You can merge this in and we'll probably pick up the work of apollofying after 23.10.

Yes, we agreed that we'll make the changes in the near future when we'll have a bit of time for it. But until then it can be merged like this.

2023-08-10 18:53 UTC, sergiubologa commented
> needs a rebase. other than that, what's missing?

@anbalase we can merge it

2023-10-16 12:25 UTC, anbalase approved these changes

2023-10-16 20:29 UTC, merged