Fix: show border for column resize
UiPath/angular-components pull request #378
Opened 2023-07-21 10:28 UTC by dan-mirescu

Show colored border for column resize instead of a drag icon.

https://uipath.atlassian.net/browse/PLT-29993

2023-07-21 11:02 UTC, gheorghitahurmuz submitted a review, later dismissed

2023-07-21 11:19 UTC, anbalase requested changes
with this change, the new UI communicates the resize anchor a bit too agressively. Pls sync w @alexandramehigh to get an idea if this is acceptable. I'd advise against. If we use this rendering, then the anchor should display/react near column header border and NOT on whole column header.

2023-07-21 11:22 UTC, anbalase commented on projects/angular/components/ui-grid/src/ui-grid.component.scss
> +    $ui-header-resize-handle-width: 1px;
are we making the handle only 1px? seems like a usability concern... pls also check w @alexandramehigh

2023-07-21 11:45 UTC, anbalase commented on projects/angular/components/ui-grid/src/ui-grid.component.scss
> +    $ui-header-resize-handle-width: 1px;
24px for optimum usability, though we could keep 15 for now if real-estate limitations won't allow it.

2023-07-24 15:12 UTC, dan-mirescu commented on projects/angular/components/ui-grid/src/ui-grid.component.scss
> +    $ui-header-resize-handle-width: 1px;
The 1px was initially added to $ui-grid-default-spacing, resulting in the requested 6 pixels. However, the new changes contain improvements in this area.

2023-07-25 06:41 UTC, anbalase commented
no changes pushed

2023-07-25 12:27 UTC, alexdudescu commented
![image](https://github.com/UiPath/angular-components/assets/17475808/590318df-ab4f-4ca6-b0f8-e636b0158229)
Having a seamless line from top to bottom when resizing (meaning row bottom borders won't show in between the blue elements) is complicated to pull off from a css standpoint and I think we should defer it. cc: @anbalase Wdyt?

2023-07-25 15:29 UTC, anbalase commented
@alexdudescu I don't think we should add these changes to 14. These are just cosmetic changes

2023-08-01 07:36 UTC, closed without merging